[package]
name = "imgui-rs-d3d12-examples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25.0" 
imgui = "0.8.0"
simple_logger = "1.13.0"
log = "0.4.14"
